name: ESP32Monitor
options:
  bundleIdPrefix: com.yourcompany
packages: {}
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.ESP32Monitor
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"  # Change to version you have installed
targets:
  ESP32Monitor:
    type: application
    platform: iOS
    sources: [ESP32Monitor]
    settings:
      base:
        INFOPLIST_FILE: ESP32Monitor/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.ESP32Monitor
        DEVELOPMENT_TEAM: "" # Add your Apple Developer Team ID here
    info:
      path: ESP32Monitor/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    dependencies:
      - framework: CoreBluetooth.framework
